import puppeteer from 'puppeteer';
import { format } from 'date-fns';
import { pl } from 'date-fns/locale';
import path from 'path';
import fs from 'fs';

interface ReservationData {
  reservationNumber: string;
  customer: {
    firstName: string;
    lastName: string;
    phone: string;
    email?: string | null;
    company?: string | null;
    address?: string | null;
    city?: string | null;
    postalCode?: string | null;
  };
  room: {
    name: string;
    maxCapacity: number;
  };
  eventType: string;
  eventDate: Date;
  startTime: string;
  durationHours: number;
  numberOfGuests: number;
  finalAmount: any;
  depositRequired: boolean;
  depositAmount?: any;
  depositDueDate?: Date | null;
  notes?: string | null;
  specialRequests?: string | null;
  autoGeneratedNotes?: string | null;
}

export const generateReservationPDF = async (reservation: ReservationData): Promise<string> => {
  const pdfDir = path.join(process.cwd(), 'pdfs');
  if (!fs.existsSync(pdfDir)) {
    fs.mkdirSync(pdfDir, { recursive: true });
  }
  
  const pdfPath = path.join(pdfDir, `${reservation.reservationNumber}.pdf`);
  
  const eventTypeLabels: Record<string, string> = {
    WEDDING: 'Wesele',
    BIRTHDAY: 'Urodziny',
    ANNIVERSARY: 'Rocznica',
    BUSINESS_MEETING: 'Spotkanie biznesowe',
    PARTY: 'Przyjęcie okolicznościowe',
    CHRISTMAS: 'Wigilia firmowa',
    BAPTISM: 'Chrzciny',
    COMMUNION: 'Komunie'
  };
  
  const html = `
    <!DOCTYPE html>
    <html lang="pl">
    <head>
      <meta charset="UTF-8">
      <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: Arial, sans-serif; padding: 40px; color: #333; }
        .header { text-align: center; margin-bottom: 40px; border-bottom: 3px solid #2563eb; padding-bottom: 20px; }
        .header h1 { color: #2563eb; font-size: 28px; margin-bottom: 10px; }
        .header p { color: #666; font-size: 14px; }
        .reservation-number { background: #2563eb; color: white; padding: 10px 20px; display: inline-block; border-radius: 5px; margin: 20px 0; font-weight: bold; }
        .section { margin-bottom: 30px; }
        .section h2 { color: #2563eb; font-size: 18px; margin-bottom: 15px; border-left: 4px solid #2563eb; padding-left: 10px; }
        .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 15px; }
        .info-item { padding: 10px; background: #f8fafc; border-radius: 5px; }
        .info-item label { font-weight: bold; color: #64748b; font-size: 12px; display: block; margin-bottom: 5px; }
        .info-item value { color: #1e293b; font-size: 14px; }
        .full-width { grid-column: 1 / -1; }
        .price-box { background: #f0f9ff; border: 2px solid #2563eb; padding: 20px; border-radius: 10px; text-align: center; margin: 20px 0; }
        .price-box .label { font-size: 14px; color: #64748b; margin-bottom: 5px; }
        .price-box .amount { font-size: 32px; font-weight: bold; color: #2563eb; }
        .footer { margin-top: 50px; padding-top: 20px; border-top: 2px solid #e2e8f0; text-align: center; color: #64748b; font-size: 12px; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>🏛️ Gościniec Rodzinny</h1>
        <p>ul. Bukowa 155, 41-600 Świętochłowice</p>
        <p>Tel: +48 XXX XXX XXX | Email: kontakt@goscinecrodzinny.pl</p>
      </div>
      
      <div style="text-align: center;">
        <div class="reservation-number">Rezerwacja: ${reservation.reservationNumber}</div>
      </div>
      
      <div class="section">
        <h2>Dane Klienta</h2>
        <div class="info-grid">
          <div class="info-item">
            <label>Imię i nazwisko</label>
            <value>${reservation.customer.firstName} ${reservation.customer.lastName}</value>
          </div>
          <div class="info-item">
            <label>Telefon</label>
            <value>${reservation.customer.phone}</value>
          </div>
          ${reservation.customer.email ? `
          <div class="info-item">
            <label>Email</label>
            <value>${reservation.customer.email}</value>
          </div>` : ''}
          ${reservation.customer.company ? `
          <div class="info-item">
            <label>Firma</label>
            <value>${reservation.customer.company}</value>
          </div>` : ''}
        </div>
      </div>
      
      <div class="section">
        <h2>Szczegóły Wydarzenia</h2>
        <div class="info-grid">
          <div class="info-item">
            <label>Typ wydarzenia</label>
            <value>${eventTypeLabels[reservation.eventType] || reservation.eventType}</value>
          </div>
          <div class="info-item">
            <label>Data</label>
            <value>${format(reservation.eventDate, 'dd.MM.yyyy', { locale: pl })}</value>
          </div>
          <div class="info-item">
            <label>Godzina rozpoczęcia</label>
            <value>${reservation.startTime}</value>
          </div>
          <div class="info-item">
            <label>Czas trwania</label>
            <value>${reservation.durationHours} godzin</value>
          </div>
          <div class="info-item">
            <label>Sala</label>
            <value>${reservation.room.name}</value>
          </div>
          <div class="info-item">
            <label>Liczba gości</label>
            <value>${reservation.numberOfGuests} os.</value>
          </div>
        </div>
      </div>
      
      ${reservation.autoGeneratedNotes ? `
      <div class="section">
        <div class="info-item full-width" style="background: #fef3c7; border-left: 4px solid #f59e0b;">
          <label>⚠️ Ważne</label>
          <value>${reservation.autoGeneratedNotes}</value>
        </div>
      </div>` : ''}
      
      <div class="price-box">
        <div class="label">Kwota do zapłaty</div>
        <div class="amount">${Number(reservation.finalAmount).toFixed(2)} PLN</div>
      </div>
      
      ${reservation.depositRequired ? `
      <div class="section">
        <h2>Zaliczka</h2>
        <div class="info-grid">
          <div class="info-item">
            <label>Kwota zaliczki</label>
            <value>${Number(reservation.depositAmount).toFixed(2)} PLN</value>
          </div>
          <div class="info-item">
            <label>Termin wpłaty</label>
            <value>${reservation.depositDueDate ? format(reservation.depositDueDate, 'dd.MM.yyyy', { locale: pl }) : '-'}</value>
          </div>
        </div>
      </div>` : ''}
      
      ${reservation.notes || reservation.specialRequests ? `
      <div class="section">
        <h2>Uwagi</h2>
        ${reservation.notes ? `<div class="info-item full-width"><label>Notatki</label><value>${reservation.notes}</value></div>` : ''}
        ${reservation.specialRequests ? `<div class="info-item full-width"><label>Specjalne życzenia</label><value>${reservation.specialRequests}</value></div>` : ''}
      </div>` : ''}
      
      <div class="footer">
        <p>Dokument wygenerowany: ${format(new Date(), 'dd.MM.yyyy HH:mm', { locale: pl })}</p>
        <p>Dziękujemy za wybór Gościniec Rodzinny!</p>
      </div>
    </body>
    </html>
  `;
  
  const browser = await puppeteer.launch({
    headless: true,
    executablePath: process.env.PUPPETEER_EXECUTABLE_PATH || undefined,
    args: ['--no-sandbox', '--disable-setuid-sandbox']
  });
  
  const page = await browser.newPage();
  await page.setContent(html);
  await page.pdf({
    path: pdfPath,
    format: 'A4',
    printBackground: true,
    margin: { top: '20px', right: '20px', bottom: '20px', left: '20px' }
  });
  
  await browser.close();
  
  return pdfPath;
};
